### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by el-conejito** [gtkforphp/cairo#25]
Hello,

I'm getting error when I try to compile. I'm running Ubuntu 16.04 with php 7.0.8. I complied and installed eosforphp/datastructures first. Thank you in advance.

/bin/bash /tmp/cairo/libtool --mode=compile cc  -I. -I/tmp/cairo -DPHP_ATOM_INC -I/tmp/cairo/include -I/tmp/cairo/main -I/tmp/cairo -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12  -DHAVE_CONFIG_H  -g -O2   -c /tmp/cairo/cairo.c -o cairo.lo
libtool: compile:  cc -I. -I/tmp/cairo -DPHP_ATOM_INC -I/tmp/cairo/include -I/tmp/cairo/main -I/tmp/cairo -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -DHAVE_CONFIG_H -g -O2 -c /tmp/cairo/cairo.c  -fPIC -DPIC -o .libs/cairo.o
In file included from /tmp/cairo/cairo.c:32:0:
/tmp/cairo/php_cairo.h:541:8: error: unknown type name ‘zend_object_value’
 extern zend_object_value cairo_surface_object_new(zend_class_entry *ce TSRMLS_DC);
        ^
In file included from /tmp/cairo/cairo.c:32:0:
/tmp/cairo/php_cairo.h:548:8: error: unknown type name ‘zend_object_value’
 extern zend_object_value cairo_font_face_object_new(zend_class_entry *ce TSRMLS_DC);

**Comment by swen100** [comment]
Hi el-conejito,

you have tried to compile the version for PHP 5 and not PHP 7. Please ensure, that you clone the correct version with:
```
git clone -b php7  https://github.com/gtkforphp/cairo.git
```
Swen

**Comment by el-conejito** [comment]
Swen,

That was the problem. Thank you for your help.

Greg
