### ISSUE TITLE
Unable to display/load fonts

### ISSUE THREAD

**Issue by harlenpd** [gtkforphp/cairo#33]
Hi guys, thanks for all the work on Cairo for PHP7, really hoping for some help please.

Following any one of the font based examples (select-font-face.php, large-font.php, etc.) I am unable to to display anything more than squiggly lines and shapes instead of text. What am I missing?

For clarification: everything has compiled successfully and I can draw shapes, but the text "Hi" is displaying as per the attached screenshot. Using PHP 7.1.9.
![cairo-text](https://user-images.githubusercontent.com/28624430/30737870-69ce0c8c-9f88-11e7-87fa-ede619ff41d5.png)

**Comment by harlenpd** [comment]
Never mind, it was an issue with my container not loading fonts correctly.
Problem solved.

**Comment by auroraeosrose** [comment]
Glad to know it's working!
